service: perfsys-slack-aws-users-activity

provider:
  name: aws
  profile: perfsys
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    APPLICATION_TOKEN: BEARER_TOKEN
    PRESENCE_TABLE: io.perfsys.serverless.cloud.slack-users-activity-atomic
  iamRoleStatements:
    -
      Resource:
        Fn::GetAtt:
          - SlackPresenceTable
          - Arn
      Effect: Allow
      Action:
        - dynamodb:PutItem

functions:
  check-presence:
    handler: collect-atomic.handler
    events:
      - schedule:
          description: Checking Slack presence
          rate: rate(5 minutes)
          enabled: true
  daily-statistics:
    handler: daily-statistics.handler

resources:
  Resources:
    SlackPresenceTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: dateTime
            AttributeType: S
        KeySchema:
          -
            AttributeName: dateTime
            KeyType: HASH

        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.PRESENCE_TABLE}
